[fix] workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,11 +21,11 @@ jobs:
       - name: Add EC2 to known_hosts
         run: |
           mkdir -p ~/.ssh
-          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || echo "Failed to add host"
+          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || echo "Host key scan failed, using StrictHostKeyChecking=no"
 
       - name: Prepare EC2 environment
         run: |
-          ssh -i ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
+          ssh -t -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
           sudo apt update
           sudo apt install -y docker-compose
           sudo usermod -aG docker ubuntu
@@ -39,7 +39,7 @@ jobs:
 
       - name: Create .env file
         run: |
-          ssh -i ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
+          ssh -t -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
           cd /home/ubuntu/Scheduler
           echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" > .env
           echo "FIREBASE_PRIVATE_KEY=\"${{ secrets.FIREBASE_PRIVATE_KEY }}\"" >> .env
@@ -49,7 +49,7 @@ jobs:
 
       - name: Deploy using Docker Compose
         run: |
-          ssh -i ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
+          ssh -t -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
           cd /home/ubuntu/Scheduler
           sudo docker-compose -f docker-compose.yml down
           sudo docker-compose -f docker-compose.yml up --build -d
